mock: True
outputdir: 'output/fullmodel/freepiemd_shear'
seed: 42
prior_samples: True
calculate_elbo: False
data_plot: False

spaces:
  lens_space:
    padding_ratio: 1.5
    Npix:
      - 128
      - 128
    distance:
      - 0.05
      - 0.05

  source_space:
    padding_ratio: 1.5
    Npix:
      - 128
      - 128
    distance:
      - 0.05
      - 0.05


data:
  noise_scale: 1.

mock_data:
  Type: 'hubble' # gaussian, hubble, fits
  gaussian:
    A: 20
    x0: 0.24
    y0: 0.17
    a00: 0.04
    a11: 0.14
  hubble:
    hubble_path: '/home/jruestig/Data/source_images/sources.npy'
    source_id: 6441
    distance: 0.04
    source_maximum: 8
  fits:
    fits_path: '/home/jruestig/Data/source_images/ngc7320.fits'
    # distance: 0.04
    distance: 0.002
    source_maximum: 500
  Lens:
    dPIE_0_b: 2.0044161
    dPIE_0_q: 1.47265484
    dPIE_0_r_s: 0.0471554
    dPIE_0_r_c: 1.85812236
    dPIE_0_th: 15.55583871
    dPIE_0_x0: 0.0320614
    dPIE_0_y0: 0.05448241
    CNFW_0_b: 1.0001
    CNFW_0_r_s: 0.3
    CNFW_0_x0: 0.0
    CNFW_0_y0: 1.5

files:
  psf_path: null
  data_path: '/home/jruestig/Data/source_images/birrer_comparison/data.fits'
  source_path: '/home/jruestig/Data/source_images/birrer_comparison/source.fits'

priors:
  source:
    center:
      mean: 0.
      sigma: 0.2
      key: 'source_center'
    covariance:
      mean: 0.2
      sigma: 1e-2
      key: 'source_covariance'
    off_diagonal:
      mean: 0.01
      sigma: 1e-2
      key: 'source_off_diagonal'
    amplitude:
      offset_mean: 2.3
      offset_std:
        - 0.5e+0
        - 1e-1
    fluctuations:
      scale:
        - 1.5e+0
        - 1e-1
      cutoff:
        - 0.1
        - 1e-2
      loglogslope:
        - -4.0
        - 5e-1

  lens:
    piemd:
      b:
        distribution: null
        mean: 1.0
        sigma: 0.0001
        N_copies: 1
      rs:
        distribution: 'log_normal'
        mean: 0.1
        sigma: 0.05
        N_copies: 1
      center:
        distribution: 'normal'
        mean: 0.
        sigma: 0.2
        N_copies: 2
      q:
        distribution: 'uniform'
        mean: 0.5 # FIXME: this should be at most 1
        sigma: 0.5
        N_copies: 1
      theta:
        distribution: 'normal'
        mean: 0.0
        sigma: 10
        N_copies: 1

    shear:
      strength:
        distribution: 'normal'
        mean: 0
        sigma: 0.07
        N_copies: 1
      theta:
        distribution: 'normal'
        mean: 0.0
        sigma: 10
        N_copies: 1
      center:
        distribution: null
        mean: 0.
        sigma: 0.2
        N_copies: 2

    offset:
      offset_mean: -0.2
      offset_std:
        - 1e-1
        - 1e-6
    fluctuations:
      fluctuations:
        - 0.5
        - 5e-2
      loglogavgslope:
        - -6.0
        - 0.7
      flexibility:
        - 0.5
        - 1.0
      asperity: null
        # - 0.1
        # - 0.5


minimization:
  resume: False
  dry_run: False
  geovi: True
  geovi_start: 3
  total_iterations: 10
  n_samples: 5 #'lambda i_iter: 6 if i_iter < 13 else 10'
  ic_newton:
    convergence_level: 2
    deltaE: 0.1
    iteration_limit: 10
    name: Newton
  ic_sampling:
    deltaE: 0.05
    iteration_limit: 25
    name: Sampling(lin)
  ic_sampling_nl:
    deltaE: 0.5
    iteration_limit: 10
    name: Sampling(nonlin)
